name: Trigger auto deployment for livemasjid-relay

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/livemasjid-relay-AutoDeployTrigger-afcf6044-2e0e-458b-a81d-f97dc04a2717.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: yusufk.azurecr.io
          username: ${{ secrets.LIVEMASJIDRELAY_REGISTRY_USERNAME }}
          password: ${{ secrets.LIVEMASJIDRELAY_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: yusufk.azurecr.io/livemasjid-relay:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LIVEMASJIDRELAY_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n livemasjid-relay -g livemasjid-rg --server yusufk.azurecr.io --username  ${{ secrets.LIVEMASJIDRELAY_REGISTRY_USERNAME }} --password ${{ secrets.LIVEMASJIDRELAY_REGISTRY_PASSWORD }}
            az containerapp update -n livemasjid-relay -g livemasjid-rg --image yusufk.azurecr.io/livemasjid-relay:${{ github.sha }}
